### ISSUE TITLE
Library functions aren't consistent with design guide

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_LSM303#2]
Ref: http://circuitpython.readthedocs.io/en/latest/docs/design_guide.html#sensor-properties-and-units

Currently have `accelerometer` and `magnetometer`. These should be `acceleration` and `magnetic`. Suggest keeping current ones and adding in the new ones.

Also, `accelerometer` is returning a list, not a tuple.

**Comment by ladyada** [comment]
ooh good catch - i'm ok with a breaking change since this is a very new driver
@kattni wanna take this one? :)

**Comment by kattni** [comment]
Sure thing! 

@ladyada to clarify: you'd rather simply alter what's there and remove the incorrect naming?

**Comment by ladyada** [comment]
yes that is correct - thank u kattni :)

**Comment by caternuson** [comment]
Closing. Fixed by #3
