### ISSUE TITLE
Need to verify acceleration and magnetic data register layout.

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_LSM303#8]
This issue being created to continue the discussion started in #7. This library is currently treating the magnetic register as 12 bit.

The size and alignment of the acceleration and magnetic data registers needs to be verified. From the [datasheet](https://cdn-shop.adafruit.com/datasheets/LSM303DLHC.PDF), it's apparent that it is 2's complement.
Accel:
![image](https://user-images.githubusercontent.com/8755041/46889895-f41f5b00-ce19-11e8-9e22-53f3e6737235.png)
Mag:
![image](https://user-images.githubusercontent.com/8755041/46889871-dce06d80-ce19-11e8-82f0-b0102738efb6.png)
But there seems to be some confusion about the size and subsequent alignment. The [datasheet](https://cdn-shop.adafruit.com/datasheets/LSM303DLHC.PDF) indicates they are 16 bit:
![image](https://user-images.githubusercontent.com/8755041/46890095-98090680-ce1a-11e8-96a0-883dd3f8aaee.png)
However, there are differences among the libraries.
Depecrated Arduino library:
- accel: https://github.com/adafruit/Adafruit_LSM303/blob/master/Adafruit_LSM303.cpp#L55
- mag: https://github.com/adafruit/Adafruit_LSM303/blob/master/Adafruit_LSM303.cpp#L80

Current Arduino library
- accel: https://github.com/adafruit/Adafruit_LSM303DLHC/blob/master/Adafruit_LSM303_U.cpp#L123
- mag: https://github.com/adafruit/Adafruit_LSM303DLHC/blob/master/Adafruit_LSM303_U.cpp#L308

Python library (based on deprecated Arduino?):
- accel: https://github.com/adafruit/Adafruit_Python_LSM303/blob/master/Adafruit_LSM303/LSM303.py#L82
- mag: https://github.com/adafruit/Adafruit_Python_LSM303/blob/master/Adafruit_LSM303/LSM303.py#L86

CircuitPython library:
- accel: https://github.com/adafruit/Adafruit_CircuitPython_LSM303/blob/master/adafruit_lsm303.py#L163
- mag: https://github.com/adafruit/Adafruit_CircuitPython_LSM303/blob/master/adafruit_lsm303.py#L180

**Comment by microbuilder** [comment]
If you look at the datasheet, values seem to be 12-bit doing the math of lsb and range.

At +/-2g on the accel, for example, it says you have 1mg per lsb. With 12-bit values this equals 4096mg or ... +/-2g. The values no longer match if you assume 16-bit data.

<img width="952" alt="screenshot 2018-10-12 at 22 41 40" src="https://user-images.githubusercontent.com/181073/46893300-bd286400-ce70-11e8-8bba-ee9d8012e15f.png">

**Comment by microbuilder** [comment]
Feel free to reopen if you feel I'm mistaken, but I'm almost certain the 12-bit shift is correct.

**Comment by microbuilder** [comment]
Hmm ... re-opening, sorry.  I see the problem, in some libs there is a shift and some there isn't. The data is almost certainly 12-bit not 16, the question is whether there should be a shift  or not. I'll have to do some further investigating if we should shift or if they values are correctly aligned out of the box with the signed-bit in the final bit position.

**Comment by microbuilder** [comment]
Bit shifting signed values with Python does maintain the signedness, which it should since the underlying ASM instructions on ARM would do the same so the >> 4 is fine. But I'll update the code to say `//16` since that is clearer.

**Comment by microbuilder** [comment]
Did some testing on real HW, see #9 for what should be the correct solution here. Thanks for bringing this up, and sorry for the back and forth in the issue. The DS really isn't very clear on this.
